services:
  guac-proxy:
    build: ./proxy
    container_name: guac-proxy
    depends_on:
      - guacd
    volumes:
      - ./logs:/logs
    # Make sure the proxy listens on the same internal Docker network
    networks:
      - guacnet

  guacd:
    container_name: guacd
    image: guacamole/guacd
    restart: unless-stopped
    networks:
      - guacnet

  # Postgres can be used as an alternative to MySQL
  guacdb:
    container_name: guacdb
    image: postgres:15
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_pass
    volumes:
      - dbdata:/var/lib/postgresql/data
      - "initdb:/docker-entrypoint-initdb.d:ro"
    restart: unless-stopped
    networks:
      - guacnet

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    depends_on:
      - guac-proxy
      - guacd
      - guacdb
    environment:
      # Route traffic destined for guacd to the guac-proxy instead
      GUACD_HOSTNAME: guac-proxy
      GUACD_PORT: 4823
      POSTGRESQL_HOSTNAME: guacdb
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USERNAME: guacamole_user
      POSTGRESQL_PASSWORD: guacamole_pass
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - "initdb:/opt/guacamole/extensions/guacamole-auth-jdbc/postgresql/schema:ro"
    networks:
      - guacnet

volumes:
  dbdata:
  initdb:
  logs:

networks:
  guacnet:
    driver: bridge
